### ISSUE TITLE
Lat / Long Missing Values

### ISSUE THREAD

**Issue by Filimoa** [gavinrozzi/njtr1#2]
Thanks for taking the time to create this. I'm noticed most of the lat / long tend to be null - do you know if this a fundamental issue with the Maryland data? I'm working on creating something similar in Python.

**Comment by gavinrozzi** [comment]
Thanks for your interest in the package! The data from this package only covers New Jersey, so I can't really comment on that state. I can say that there are a number of rows that have missing lat / lons. That is a limitation from the way local police departments code the data. I wrote another package that interfaces with NJ's state geocoding service that has some functions that can geocode these rows - when I have time I plan to pursue tighter integration with this package.
